#!/usr/bin/env bash
# =============================================================================
# scripts/entrypoint.sh  —  code-server container startup script
# =============================================================================
# Responsibilities:
#   1. Ensure required directories exist in the mounted volume.
#   2. Copy default VS Code settings on first run (non-destructive).
#   3. Install VS Code extensions on first run.
#   4. Hand off execution to code-server with the correct CLI flags.
#
# This script runs as root (see docker-compose.yml).
# The host filesystem is mounted at /host and fully accessible.
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
DATA_DIR="/home/coder/.local/share/code-server"
SETTINGS_FILE="${DATA_DIR}/User/settings.json"
EXTENSIONS_DIR="${DATA_DIR}/extensions"
SENTINEL="${DATA_DIR}/.extensions_initialized"
DEFAULT_SETTINGS_SRC="/etc/code-server/default-settings.json"

# ---------------------------------------------------------------------------
# 1. Ensure directories exist (volume may be empty on first run)
# ---------------------------------------------------------------------------
mkdir -p \
    "${DATA_DIR}/User" \
    "${EXTENSIONS_DIR}"

# ---------------------------------------------------------------------------
# 2. Copy default settings on first run
#    We only copy if the user hasn't already created their own settings file.
# ---------------------------------------------------------------------------
if [ ! -f "${SETTINGS_FILE}" ] && [ -f "${DEFAULT_SETTINGS_SRC}" ]; then
    echo "[entrypoint] First run — copying default VS Code settings..."
    cp "${DEFAULT_SETTINGS_SRC}" "${SETTINGS_FILE}"
fi

# ---------------------------------------------------------------------------
# 3. SSH → Host setup
#    Runs on every start (not just first run) so that permissions are always
#    correct even after a volume mount changes the key file.
# ---------------------------------------------------------------------------
SSH_KEY="/home/coder/.ssh/id_ed25519"
SSH_DIR="/home/coder/.ssh"
ROOT_SSH_DIR="/root/.ssh"

mkdir -p "${SSH_DIR}" "${ROOT_SSH_DIR}"
chmod 700 "${SSH_DIR}" "${ROOT_SSH_DIR}"

if [ -f "${SSH_KEY}" ]; then
    chmod 600 "${SSH_KEY}"
    echo "[entrypoint] SSH key found — permissions set (600)."
else
    echo "[entrypoint] WARNING: SSH key not found at ${SSH_KEY}."
    echo "[entrypoint]          Follow docs/ssh-setup-guide.md to generate"
    echo "[entrypoint]          and place the key at ./secrets/ssh_host_key."
fi

# Write SSH client config for both /home/coder and /root (container runs as root)
for SSH_CONF_DIR in "${SSH_DIR}" "${ROOT_SSH_DIR}"; do
    cat > "${SSH_CONF_DIR}/config" << EOF
# Auto-generated by entrypoint.sh on container start — do not edit manually.
# Edit SSH_HOST / SSH_USER / SSH_PORT in .env and restart the container.

Host ${SSH_HOST:-host.docker.internal} host.docker.internal host.orb.internal
    User ${SSH_USER:-}
    Port ${SSH_PORT:-22}
    IdentityFile /home/coder/.ssh/id_ed25519
    StrictHostKeyChecking accept-new
    ServerAliveInterval 30
    ServerAliveCountMax 3
    ConnectTimeout 10
    ForwardAgent no
EOF
    chmod 600 "${SSH_CONF_DIR}/config"
done

echo "[entrypoint] SSH client config written."

# Make the ssh-to-host script executable (it is mounted :ro so we can't chmod
# the mount itself, but the container sees it as executable if we set the bit
# on the source file — this chmod is a no-op safety net).
chmod +x /usr/local/bin/ssh-to-host 2>/dev/null || true

# ---------------------------------------------------------------------------
# 4. Install extensions on first run
#    A sentinel file prevents reinstalling on every container start.
#    Add or remove extension IDs from the list below as needed.
# ---------------------------------------------------------------------------
if [ ! -f "${SENTINEL}" ]; then
    echo "[entrypoint] First run — installing VS Code extensions..."
    echo "[entrypoint] This may take a few minutes. Grab a coffee ☕"

    EXTENSIONS=(
        "github.copilot"
        "github.copilot-chat"
    )

    for ext in "${EXTENSIONS[@]}"; do
        echo "[entrypoint]   → ${ext}"
        code-server --install-extension "${ext}" \
            --extensions-dir "${EXTENSIONS_DIR}" \
            2>&1 | grep -v "^$" || \
            echo "[entrypoint]   WARNING: Could not install ${ext}. It can be installed manually from the Extensions panel."
    done

    touch "${SENTINEL}"
    echo "[entrypoint] Extension installation complete."
fi

# ---------------------------------------------------------------------------
# 5. Start code-server
#    --bind-addr     : listen on all interfaces inside the container on port 8080
#    --auth          : 'none' disables the login screen (Pangolin SSO handles auth)
#                      set AUTH=password in .env to re-enable the built-in prompt
#    --user-data-dir : point to the volume-backed data directory
#    --extensions-dir: use the persistent extensions directory
#    Last argument   : default folder to open in the editor
# ---------------------------------------------------------------------------
echo "[entrypoint] Starting code-server..."

exec code-server \
    --bind-addr "0.0.0.0:8080" \
    --auth "${AUTH:-none}" \
    --user-data-dir "${DATA_DIR}" \
    --extensions-dir "${EXTENSIONS_DIR}" \
    "${DEFAULT_WORKSPACE:-/home/coder/projects}"
